[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.web"

[deploy]
startCommand = "python manage.py migrate --run-syncdb && python manage.py shell -c \"import os; os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'qfieldcloud.settings'); import django; django.setup(); from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('admin', 'admin@example.com', 'admin123') if not User.objects.filter(username='admin').exists() else print('Superuser already exists')\" && python manage.py collectstatic --noinput && gunicorn qfieldcloud.wsgi:application --bind 0.0.0.0:${PORT:-8000} --timeout 120 --workers 3 --threads 2"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[variables]
DJANGO_SETTINGS_MODULE = "qfieldcloud.settings"
PYTHONUNBUFFERED = "1"
DEBUG = "0"
ENVIRONMENT = "production"
DJANGO_ALLOWED_HOSTS = "*"

# QFieldCloud Core Settings
QFIELDCLOUD_HOST = "railway.app"

# Security Keys (IMPORTANT: Change these in Railway UI!)
SECRET_KEY = "temporary-secret-key-change-me-in-production-at-least-50-characters-long"
SALT_KEY = "temporary-salt-key-change-me-in-production-32-chars"

# Database Settings (NEON)
DATABASE_URL = "postgresql://neondb_owner:npg_ZmS1lhvnx9HW@ep-late-cake-a8xp8sl0-pooler.eastus2.azure.neon.tech/neondb?sslmode=require&channel_binding=require"

# Alternative individual settings
POSTGRES_HOST = "ep-late-cake-a8xp8sl0-pooler.eastus2.azure.neon.tech"
POSTGRES_PORT = "5432"
POSTGRES_DB = "neondb"
POSTGRES_USER = "neondb_owner"
POSTGRES_PASSWORD = "npg_ZmS1lhvnx9HW"
POSTGRES_SSLMODE = "require"

# Storage Settings (Filesystem by default)
STORAGES = "filesystem"

# Storage Environment Variables (Required for filesystem storage - using dummy values)
STORAGE_ACCESS_KEY_ID = "dummy-key-for-filesystem-storage"
STORAGE_SECRET_ACCESS_KEY = "dummy-secret-for-filesystem-storage"
STORAGE_BUCKET_NAME = "dummy-bucket-for-filesystem-storage"
STORAGE_REGION_NAME = "us-east-1"
STORAGE_ENDPOINT_URL = ""

# Email Settings (Optional - configure in Railway UI if needed)
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = "587"
EMAIL_USE_TLS = "1"
EMAIL_HOST_USER = ""
EMAIL_HOST_PASSWORD = ""

# Email Verification Settings
ACCOUNT_EMAIL_VERIFICATION = "optional"
EMAIL_VERIFICATION = "optional"

# Gunicorn Settings (already configured in start command)
GUNICORN_TIMEOUT_S = "120"
GUNICORN_MAX_REQUESTS = "1000"
GUNICORN_WORKERS = "3"
GUNICORN_THREADS = "2"

# Feature Flags
QFIELDCLOUD_SUBSCRIPTIONS_ENABLED = "1"
QFIELDCLOUD_INVITATIONS_ENABLED = "1"
QFIELDCLOUD_REGISTRATION_ENABLED = "1"
QFIELDCLOUD_ADMIN_ACCOUNT_CREATION_ENABLED = "1"

# Sentry (Optional - add DSN in Railway UI)
SENTRY_DSN = ""
SENTRY_ENVIRONMENT = "production"
SENTRY_SAMPLE_RATE = "0.1"